#define MAX_REQ_LINE 1024
#define DEFAULT_PORT 8080
#define DEFAULT_PORT_STR "8080"
#define DEFAULT_PATH "/home/psikora/"
#define LOGFILE_NAME "http.log"
#define LOCKFILE_NAME "daemon.lock"
#define MAX_SIZE_OF_PORT 7 
#define MAX_SIZE_OF_PATH 500
#define MAX_SIZE_OF_FILE_NAME 40
#define SIZE_OF_ARRAY_ONE_EL 2
#define MAX_SIZE_OF_CONF_FILE 200
